name: Simple Kotlin to Java Converter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Convert Kotlin to Java
      run: |
        # Create output directory
        mkdir -p converted-java/com/medtronic/design/android/util
        
        # Read the Kotlin file and convert to Java
        input_file="design/src/main/java/com/medtronic/design/android/util/AutomationIDs.kt"
        output_file="converted-java/com/medtronic/design/android/util/AutomationIDs.java"
        
        # Perform the conversion
        sed -e 's/object /public class /g' \
            -e 's/const val /public static final String /g' \
            -e 's/fun /public static String /g' \
            -e 's/Int/int/g' \
            -e 's/: String//g' \
            -e 's/: Int//g' \
            "$input_file" > "$output_file"
        
        # Manual refinement for better Java syntax
        cat > "$output_file" << 'EOF'
        package com.medtronic.design.android.util;
        
        public class AutomationIDs {
            public static class Common {
                public static final String LABEL = "label";
                public static final String ICON = "icon";
                public static final String TITLE = "title";
                public static final String PLACEHOLDER = "placeholder";
                public static final String POPOVER = "popover";
                public static final String OPTION = "option_";
                public static final String INDICATOR = "indicator";
            }
        
            public static class Banner {
                public static final String ICON = "banner_icon";
                public static final String MESSAGE = "banner_message";
                public static final String LINK = "banner_link_text";
                public static final String ACTION = "banner_action_button";
            }
        
            public static class BillboardBanner {
                public static final String LOGO = "bbb_logo";
                public static final String APP_NAME = "bbb_app_name";
                public static final String MENU = "bbb_menu";
                public static final String CONTENT = "bbb_content";
                public static final String HELP_LINK = "bbb_help_link";
                public static final String ACTION_BUTTON = "bbb_action_button";
                public static final String PAGINATION = "bbb_pagination";
            }
        
            public static class Button {
                public static final String LABEL = Common.LABEL;
                public static final String ICON = Common.ICON;
            }
        
            public static class Card {
                public static final String THUMBNAIL = "thumbnail";
                public static final String TITLE = Common.TITLE;
                public static final String SUBTEXT = "subtext";
                public static final String INDICATOR = Common.INDICATOR;
            }
        
            public static class ChoicePicker {
                public static final String LABEL = Common.LABEL;
                public static final String ICON = Common.ICON;
                public static final String INDICATOR = Common.INDICATOR;
            }
        
            public static class Dialog {
                public static final String ICON = Common.ICON;
                public static final String TITLE = Common.TITLE;
                public static final String DESCRIPTION = "description";
                public static final String PRIMARY_BUTTON = "primary_button";
                public static final String SECONDARY_BUTTON = "secondary_button";
            }
        
            public static class FormField {
                public static final String LABEL = Common.LABEL;
                public static final String PLACEHOLDER = Common.PLACEHOLDER;
                public static final String SUPPORTING_TEXT = "supporting_text";
                public static final String CLEAR = "clear";
                public static final String TRAILING = "trailing";
            }
        
            public static class KeypadField {
                public static final String PLACEHOLDER = Common.PLACEHOLDER;
                public static final String VALUE = "value";
            }
        
            public static class ActionMenu {
                public static final String MENU = "medtronic_action_menu";
                public static final String BUTTON = "button";
                public static final String POPOVER = Common.POPOVER;
            }
        
            public static class DropdownMenu {
                public static final String MENU = "menu";
                public static final String SELECTOR = "selector";
                public static final String SELECTED_OPTION_LABEL = "selected_option_label";
                public static final String POPOVER = Common.POPOVER;
                public static final String OPTION_LABEL = "option_label";
                public static final String OPTION_LEADING_ICON = "option_leading_icon";
                public static final String OPTION_TRAILING_ICON = "option_trailing_icon";
                public static final String SELECTION_INDICATOR = "selection_indicator";
            }
        
            public static class Paginator {
                public static final String DOT = "dot_";
                public static final String ACTIVE_DOT = "active_dot_";
                public static final String CURRENT_PAGE = "current_page";
                public static final String TOTAL_PAGES = "total_pages";
            }
        
            public static class BottomSheet {
                public static final String DRAG_HANDLE = "drag_handle";
                public static final String BACK_BUTTON = "back_button";
                public static final String TITLE = Common.TITLE;
                public static final String CLOSE_BUTTON = "close";
            }
        
            public static String getOptionAutomationId(int index) {
                return Common.OPTION + index;
            }
        }
        EOF
        
    - name: Verify conversion
      run: |
        echo "=== Converted Java file ==="
        cat converted-java/com/medtronic/design/android/util/AutomationIDs.java
        echo ""
        echo "=== File size comparison ==="
        echo "Original Kotlin file:"
        wc -l design/src/main/java/com/medtronic/design/android/util/AutomationIDs.kt
        echo "Converted Java file:"
        wc -l converted-java/com/medtronic/design/android/util/AutomationIDs.java
        
    - name: Upload converted Java file
      uses: actions/upload-artifact@v4
      with:
        name: kotlin-to-java-conversion
        path: converted-java/
        retention-days: 30
        
    - name: Create release-ready archive
      run: |
        cd converted-java
        tar -czf ../AutomationIDs-java.tar.gz .
        cd ..
        
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: AutomationIDs-java-archive
        path: AutomationIDs-java.tar.gz
        retention-days: 30
